# 网站标题
title: PopTartSodo
# 网站标题后缀
suffix: Blog
# 作者名称
author: Sodo
# 网站关键字
keyword: Sodo
#false是否开启文章背景图显示(随机图片)
is_article_img: false 
# 网站描述
web_description: 描述
# 首页文章布局 默认 'card' 可选择 'block-card'
home_layout: card
# 导航名称
menus_title:
  home: HOME
  archive: ARCHIVE
  categories: CATEGORIES
  tags: TAGS
  links: LINKS
  about: ABOUT
# 导航 （不建议修改）
menus:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  links: /links
  about: /about
  
# logo
logo: /image/logo.png
# 网页标签上那个小图标 一定要用本地存储
icon: /image/Console03.png
# 每个页面的展示的图标和一句话
headers:
    home: {
      message: "首页这里应该有一句话，你想想写点什么？",
      icon: "/image/Console01.png"
    }
    archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: "居然用了 year 年一共才写了 number 篇文章!",
      icon: "/image/Floppy Disk.png"
    }
    tags: {
      message: "这里是一些展示的标签",
      icon: "/image/Piano Keyboard.png"
    }
    links: {
      message: "我和我的小伙伴们",
      icon: "/image/Headphone.png"
    }
    categories: {
      message: "文章分类",
      icon: "/image/Radio Tape.png"
    }
#    about: {
#      message: "关于我们",
#      icon: "/image/Console02.png"
#    }


# 网页访问统计
web_analytics:  # 网页访问统计
  enable: true # 默认为false，启用网页统计改为true即可 
  google: UA-277151711-1
  gtag: G-1V1Z7EKXTB
busuanzi:
  enable: true




# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png',
    #跳转链接    
    toUrl: 'https://github.com/PopTartSodo/PopTartSodo.github.io'
  }
# 友情链接
linksList:
  - {
    title: 'Sodo Repository',
    intro: 'Repository',
    link: 'https://github.com/PopTartSodo/PopTartSodo.github.io',
    image: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgIMG_7327.jpeg'
  }

#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
# https://api.ixiaowai.cn/gqapi/gqapi.php
# https://tuapi.eees.cc/api.php?type=302&category=fengjing
default_cover: ""
